### PR TITLE
Support for building self-contained binaries for easier installation

### LINKED ISSUE #29: Suggestion: A self-contained binary for easier installation
In my organization, dozens of devs are starting to use onelogin-aws-cli(Thank you very much for creating/maintaining this!). The only and largest struggle for me is that many of them already has a working python2 and/or python3 envs each with virutalenv(s) or no virtualenv at all. There seems like no uniform, easy way to keep one's `onelogin-aws-login` installation up-to-date and accessible whatever python/virutualenv he/she uses for ones own development work.

## Possible solution

While hanging around GitHub, I got to know that there's a tool named [pex](https://github.com/pantsbuild/pex) which is capable of creating a self-contained executable python env for your app.

See how it works in the wild at e.g.: https://github.com/datawire/forge/commit/6fd6d6d048e345fd95ea6e683c3acff1c0f2ea4e

Would you mind hosting the self-contained binary at GitHub releases of this project once if I contributed the script for automating it?

Thanks!

### PR DESCRIPTION
**Pull request by mumoshu**
This adds `scripts/build.sh` which produces a pex binary `dist/onelogin-aws-login`.

The pex binary supports multiple archs/platforms - currently, it is runnable on both linux/macOS, x86_64/i686.
The existing way to install onelogin-aws-login with `pip install` is still supported.

Note that a pex binary doesn't contain a python runtime. You still need to install python3 in order to run the onelogin-aws-login command.
However, this will still allow you to install onelogin-aws-login without polluting your python env. Also, installing onelogin-aws-login is easier as it is just a matter of running `curl -o onelogin-aws-login <onelogin-aws-login release> && chmod +x onelogin-aws-login`.

Resolves #29

---

This is verified to work by:

- Running `pip install -e .` and then `onelogin-aws-login`
- Running `scripts/build.sh` and then `dist/onelogin-aws-login`
- Running `docker build -t onelogin-aws-login-test .` with Dockerfile:
  ```
  FROM alpine:3.7

  RUN apk add --update --no-cache python3

  ADD dist/onelogin-aws-login /
  ```
  and running `docker run --rm -it onelogin-aws-login /onelogin-aws-login -h`

### CODE REVIEW

**Comment by slycoder** [comment]
Apologies for the late response.  Thanks for submitting this, we'd love to get it in!  Could you update the conflicts on the PR to accommodate some other changes that have landed in the interim?

**Comment by mumoshu** [comment]
@slycoder No worry, thanks for taking your time!

Just fixed the conflict - resolving it produced no commit diff because it was just due to a fix to a line-ending.

**Comment by mumoshu** [comment]
@slycoder Just for your notice, the last travis build for this is failing due to the same errors seen in [the current master](https://travis-ci.org/physera/onelogin-aws-cli/builds/334505000?utm_source=github_status&utm_medium=notification).

**Comment by slycoder** [comment]
Sorry about the delay.  I'll go ahead and merge.

**Pull request merged**
