### PR TITLE
Extract user role query

### PR DESCRIPTION
**Pull request by drewsonne**
Extracted user cli prompt from OneloginAWS class to be usable by daemon client.

### CODE REVIEW

**Comment by slycoder** [comment]
Mind merging changes from master into this PR?  It'll make the diff easier to see =).

**Comment by drewsonne** [comment]
I've rebased this fork now. 


On another note, given the changes from https://github.com/physera/onelogin-aws-cli/pull/71 I'm going to review the changes I made to this repo in the last little while and see how many are still relevant. 

I'll spend some time seeing if there are any changes which are no longer relevant given the longer session time.

**Comment by slycoder** [comment]
Yeah, the changes in this PR aren't super necessary any more but it does make things a little cleaner so I'd vote for merging this.

**Comment by drewsonne** [comment]
@slycoder agreed! I felt the same. A bit cleaner, but definitely not vital. I'm happy to merge it in too, if it's all the same.

**Pull request merged**
